#!/usr/bin/env bash
# =============================================================================
# JACI spack-stack Tcl module validation
# =============================================================================
#
# Purpose
# -------
# Validate the Tcl module tree generated by the JACI spack-stack-inpe test
# environment.
#
# Context
# -------
# The generated Tcl modules for the validated JACI GCC 12.3 target may not
# expose short module names such as:
#
#   stack-gcc/12.3.0
#   stack-cray-mpich/8.1.31
#   jedi-mpas-env/1.0.0
#
# Instead, the module tree may expose the meta environment through the full
# hierarchical name:
#
#   cray-mpich/8.1.31/none/none/jedi-mpas-env/1.0.0
#
# This script detects and loads the available JEDI MPAS environment module from
# the generated Tcl module tree.
#
# How to use
# ----------
# Run after `spack install` and `spack module tcl refresh -y`:
#
#   bash scripts/run_jaci_module_validation.sh
#
# Optional environment overrides:
#
#   PROJECT_ROOT=/p/projetos/monan_das/$USER
#   TEST_ID=spack-stack-inpe-test-release-2.1-gcc12
#   ENV_NAME=jaci-mpas-jedi-gcc12-craympich
#
# =============================================================================

set -euo pipefail

export PROJECT_ROOT="${PROJECT_ROOT:-/p/projetos/monan_das/${USER}}"
export TEST_ID="${TEST_ID:-spack-stack-inpe-test-release-2.1-gcc12}"
export WORK_ROOT="${PROJECT_ROOT}/work/${TEST_ID}"
export LOG_ROOT="${PROJECT_ROOT}/logs/${TEST_ID}"
export ENV_NAME="${ENV_NAME:-jaci-mpas-jedi-gcc12-craympich}"

export SPACK_STACK_DIR="${WORK_ROOT}/spack-stack"
export MODULE_ROOT="${SPACK_STACK_DIR}/envs/${ENV_NAME}/modules"

mkdir -p "${LOG_ROOT}"

cd "${SPACK_STACK_DIR}"

source configs/sites/tier2/jaci/setup.sh

if [ ! -d "${MODULE_ROOT}" ]; then
  echo "[ERROR] Module root not found: ${MODULE_ROOT}" >&2
  exit 1
fi

module use "${MODULE_ROOT}"

module avail 2>&1 | tee "${LOG_ROOT}/15_module_avail_generated.txt"

# Prefer the full hierarchical JEDI MPAS environment module observed on JACI.
if module avail cray-mpich/8.1.31/none/none/jedi-mpas-env/1.0.0 2>&1 | grep -q "jedi-mpas-env"; then
  JEDI_ENV_MODULE="cray-mpich/8.1.31/none/none/jedi-mpas-env/1.0.0"
elif module avail jedi-mpas-env/1.0.0 2>&1 | grep -q "jedi-mpas-env"; then
  JEDI_ENV_MODULE="jedi-mpas-env/1.0.0"
else
  echo "[ERROR] Could not find jedi-mpas-env module in ${MODULE_ROOT}" >&2
  find "${MODULE_ROOT}" -type f | sort | tee "${LOG_ROOT}/15_generated_module_files.txt"
  exit 1
fi

echo "[INFO] Loading ${JEDI_ENV_MODULE}"
module load "${JEDI_ENV_MODULE}"

module list 2>&1 | tee "${LOG_ROOT}/16_module_list_stack_loaded.txt"

{
  echo "[INFO] Tool resolution after loading ${JEDI_ENV_MODULE}"
  command -v cmake || true
  command -v ecbuild || true
  command -v python || true
  command -v nccmp || true
  command -v h5dump || true
  command -v h5diff || true
} | tee "${LOG_ROOT}/17_which_tools.txt"

if command -v python >/dev/null 2>&1; then
  python --version | tee "${LOG_ROOT}/18_python_version.txt"
  python -c "import mpi4py; print('mpi4py ok')" | tee "${LOG_ROOT}/19_python_mpi4py_check.txt"
  python -c "import netCDF4; print('netCDF4 ok')" | tee "${LOG_ROOT}/20_python_netcdf4_check.txt"
else
  echo "[ERROR] python not found after loading ${JEDI_ENV_MODULE}" >&2
  exit 1
fi

echo "[INFO] Module validation finished successfully."
