# Site setup for JACI.
# Generated by jaci-spack-stack-bootstrap.
#
# This file prepares the Cray module path and loads the toolchain modules
# configured in config/jaci.env.

module --force purge || module purge || true

if [ -d "/opt/cray/pe/modulefiles" ]; then
  module use "/opt/cray/pe/modulefiles"
fi
if [ -d "/opt/cray/modulefiles" ]; then
  module use "/opt/cray/modulefiles"
fi
if [ -d "/opt/cray/pe/craype-targets/default/modulefiles" ]; then
  module use "/opt/cray/pe/craype-targets/default/modulefiles"
fi
if [ -d "/p/app/modulefiles" ]; then
  module use "/p/app/modulefiles"
fi
if [ -d "/opt/cray/pals/modulefiles" ]; then
  module use "/opt/cray/pals/modulefiles"
fi

module load PrgEnv-gnu/8.6.0 || {
  echo "ERROR: failed to load PrgEnv-gnu/8.6.0." >&2
  return 1 2>/dev/null || exit 1
}

# Normalize GNU compiler modules before selecting the validated CrayPE backend.
# JACI may leave/reintroduce a generic module such as gcc/12.3.0/zstd/1.5.7,
# which conflicts with gcc-native/12.3.
__JACI_TARGET_COMPILER="gcc-native/12.3"
IFS=':' read -r -a __JACI_LOADED_MODULES <<< "${LOADEDMODULES:-}"
for __JACI_MODULE in "${__JACI_LOADED_MODULES[@]}"; do
  case "${__JACI_MODULE}" in
    gcc/*|gcc-native/*)
      if [[ "${__JACI_MODULE}" != "${__JACI_TARGET_COMPILER}" ]]; then
        module unload "${__JACI_MODULE}" || {
          echo "ERROR: failed to unload conflicting compiler module ${__JACI_MODULE}." >&2
          unset __JACI_TARGET_COMPILER __JACI_MODULE __JACI_LOADED_MODULES
          return 1 2>/dev/null || exit 1
        }
      fi
      ;;
  esac
done
unset __JACI_MODULE __JACI_LOADED_MODULES

module load "${__JACI_TARGET_COMPILER}" || {
  echo "ERROR: failed to load validated compiler ${__JACI_TARGET_COMPILER}." >&2
  unset __JACI_TARGET_COMPILER
  return 1 2>/dev/null || exit 1
}
unset __JACI_TARGET_COMPILER

module load craype-x86-turin || { echo "ERROR: failed to load craype-x86-turin." >&2; return 1 2>/dev/null || exit 1; }
module load cray-mpich/8.1.31 || { echo "ERROR: failed to load cray-mpich/8.1.31." >&2; return 1 2>/dev/null || exit 1; }
module load libfabric/1.22.0 || { echo "ERROR: failed to load libfabric/1.22.0." >&2; return 1 2>/dev/null || exit 1; }
module load cray-pals/1.6.1 || { echo "ERROR: failed to load cray-pals/1.6.1." >&2; return 1 2>/dev/null || exit 1; }
