# Site setup for JACI.
# Generated by jaci-spack-stack-bootstrap.
#
# This file prepares the Cray module path and loads the toolchain modules
# configured in config/jaci.env.

module --force purge || module purge || true

if [ -d "/opt/cray/pe/modulefiles" ]; then
  module use "/opt/cray/pe/modulefiles"
fi
if [ -d "/opt/cray/modulefiles" ]; then
  module use "/opt/cray/modulefiles"
fi
if [ -d "/opt/cray/pe/craype-targets/default/modulefiles" ]; then
  module use "/opt/cray/pe/craype-targets/default/modulefiles"
fi
if [ -d "/p/app/modulefiles" ]; then
  module use "/p/app/modulefiles"
fi
if [ -d "/opt/cray/pals/modulefiles" ]; then
  module use "/opt/cray/pals/modulefiles"
fi

module load PrgEnv-gnu/8.6.0
module unload gcc-native/13.2 2>/dev/null || true
module load gcc-native/12.3
module load craype-x86-turin
module load cray-mpich/8.1.31
module load libfabric/1.22.0
module load cray-pals/1.6.1
